---
- hosts: all

  user: vagrant

  sudo: true

  tasks:
  - name: install packages
    apt: pkg={{item}} state=latest
    with_items:
      - autoconf
      - automake
      - bison
      - build-essential
      - ca-certificates
      - curl
      - git
      - libc6-dev
      - libcurl4-openssl-dev
      - libncurses-dev
      - libreadline6
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libv8-dev
      - libxml2-dev
      - libxslt1-dev
      - libyaml-dev
